




/*
     FILE ARCHIVED ON 9:34:44 oct. 17, 2016 AND RETRIEVED FROM THE
     INTERNET ARCHIVE ON 0:03:12 nov. 25, 2016.
     JAVASCRIPT APPENDED BY WAYBACK MACHINE, COPYRIGHT INTERNET ARCHIVE.

     ALL OTHER CONTENT MAY ALSO BE PROTECTED BY COPYRIGHT (17 U.S.C.
     SECTION 108(a)(3)).
*/
google.maps.__gjsload__('geometry', function(_){'use strict';var vw=function(a,b){return Math.abs(_.$a(b-a,-180,180))},ww=function(a,b,c,d,e){if(!d){c=vw(a.lng(),c)/vw(a.lng(),b.lng());if(!e)return e=Math.sin(_.Sb(a.lat())),e=Math.log((1+e)/(1-e))/2,b=Math.sin(_.Sb(b.lat())),_.Tb(2*Math.atan(Math.exp(e+c*(Math.log((1+b)/(1-b))/2-e)))-Math.PI/2);a=e.fromLatLngToPoint(a);b=e.fromLatLngToPoint(b);return e.fromPointToLatLng(new _.I(a.x+c*(b.x-a.x),a.y+c*(b.y-a.y))).lat()}e=_.Sb(a.lat());a=_.Sb(a.lng());d=_.Sb(b.lat());b=_.Sb(b.lng());c=_.Sb(c);return _.$a(_.Tb(Math.atan2(Math.sin(e)*
Math.cos(d)*Math.sin(c-b)-Math.sin(d)*Math.cos(e)*Math.sin(c-a),Math.cos(e)*Math.cos(d)*Math.sin(a-b))),-90,90)},xw=_.na(),yw={containsLocation:function(a,b){for(var c=_.$a(a.lng(),-180,180),d=!!b.get("geodesic"),e=b.get("latLngs"),f=b.get("map"),f=!d&&f?f.getProjection():null,g=!1,h=0,l=e.getLength();h<l;++h)for(var n=e.getAt(h),q=0,r=n.getLength();q<r;++q){var u=n.getAt(q),x=n.getAt((q+1)%r),A=_.$a(u.lng(),-180,180),C=_.$a(x.lng(),-180,180),D=Math.max(A,C),A=Math.min(A,C);(180<D-A?c>=D||c<A:c<D&&
c>=A)&&ww(u,x,c,d,f)<a.lat()&&(g=!g)}return g||yw.isLocationOnEdge(a,b)},isLocationOnEdge:function(a,b,c){c=c||1E-9;var d=_.$a(a.lng(),-180,180),e=b instanceof _.Ce,f=!!b.get("geodesic"),g=b.get("latLngs");b=b.get("map");b=!f&&b?b.getProjection():null;for(var h=0,l=g.getLength();h<l;++h)for(var n=g.getAt(h),q=n.getLength(),r=e?q:q-1,u=0;u<r;++u){var x=n.getAt(u),A=n.getAt((u+1)%q),C=_.$a(x.lng(),-180,180),D=_.$a(A.lng(),-180,180),H=Math.max(C,D),K=Math.min(C,D);if(C=1E-9>=Math.abs(_.$a(C-D,-180,180))&&
(Math.abs(_.$a(C-d,-180,180))<=c||Math.abs(_.$a(D-d,-180,180))<=c))var C=a.lat(),D=Math.min(x.lat(),A.lat())-c,G=Math.max(x.lat(),A.lat())+c,C=C>=D&&C<=G;if(C)return!0;if(180<H-K?d+c>=H||d-c<=K:d+c>=K&&d-c<=H)if(x=ww(x,A,d,f,b),Math.abs(x-a.lat())<c)return!0}return!1}};var zw={computeHeading:function(a,b){var c=_.Vb(a),d=_.Wb(a);a=_.Vb(b);b=_.Wb(b)-d;return _.$a(_.Tb(Math.atan2(Math.sin(b)*Math.cos(a),Math.cos(c)*Math.sin(a)-Math.sin(c)*Math.cos(a)*Math.cos(b))),-180,180)},computeOffset:function(a,b,c,d){b/=d||6378137;c=_.Sb(c);var e=_.Vb(a);a=_.Wb(a);d=Math.cos(b);b=Math.sin(b);var f=Math.sin(e),e=Math.cos(e),g=d*f+b*e*Math.cos(c);return new _.E(_.Tb(Math.asin(g)),_.Tb(a+Math.atan2(b*e*Math.sin(c),d-f*g)))},computeOffsetOrigin:function(a,b,c,d){c=_.Sb(c);b/=d||
6378137;d=Math.cos(b);var e=Math.sin(b)*Math.cos(c);b=Math.sin(b)*Math.sin(c);c=Math.sin(_.Vb(a));var f=e*e*d*d+d*d*d*d-d*d*c*c;if(0>f)return null;var g=e*c+Math.sqrt(f),g=g/(d*d+e*e),h=(c-e*g)/d,g=Math.atan2(h,g);if(g<-Math.PI/2||g>Math.PI/2)g=e*c-Math.sqrt(f),g=Math.atan2(h,g/(d*d+e*e));if(g<-Math.PI/2||g>Math.PI/2)return null;a=_.Wb(a)-Math.atan2(b,d*Math.cos(g)-e*Math.sin(g));return new _.E(_.Tb(g),_.Tb(a))},interpolate:function(a,b,c){var d=_.Vb(a),e=_.Wb(a),f=_.Vb(b),g=_.Wb(b),h=Math.cos(d),
l=Math.cos(f);b=zw.rf(a,b);var n=Math.sin(b);if(1E-6>n)return new _.E(a.lat(),a.lng());a=Math.sin((1-c)*b)/n;c=Math.sin(c*b)/n;b=a*h*Math.cos(e)+c*l*Math.cos(g);e=a*h*Math.sin(e)+c*l*Math.sin(g);return new _.E(_.Tb(Math.atan2(a*Math.sin(d)+c*Math.sin(f),Math.sqrt(b*b+e*e))),_.Tb(Math.atan2(e,b)))},rf:function(a,b){var c=_.Vb(a);a=_.Wb(a);var d=_.Vb(b);b=_.Wb(b);return 2*Math.asin(Math.sqrt(Math.pow(Math.sin((c-d)/2),2)+Math.cos(c)*Math.cos(d)*Math.pow(Math.sin((a-b)/2),2)))},computeDistanceBetween:function(a,
b,c){c=c||6378137;return zw.rf(a,b)*c},computeLength:function(a,b){b=b||6378137;var c=0;a instanceof _.yc&&(a=a.getArray());for(var d=0,e=a.length-1;d<e;++d)c+=zw.computeDistanceBetween(a[d],a[d+1],b);return c},computeArea:function(a,b){return Math.abs(zw.computeSignedArea(a,b))},computeSignedArea:function(a,b){b=b||6378137;a instanceof _.yc&&(a=a.getArray());for(var c=a[0],d=0,e=1,f=a.length-1;e<f;++e)d+=zw.Al(c,a[e],a[e+1]);return d*b*b},Al:function(a,b,c){return zw.Bl(a,b,c)*zw.Em(a,b,c)},Bl:function(a,
b,c){var d=[a,b,c,a];a=[];for(c=b=0;3>c;++c)a[c]=zw.rf(d[c],d[c+1]),b+=a[c];b/=2;d=Math.tan(b/2);for(c=0;3>c;++c)d*=Math.tan((b-a[c])/2);return 4*Math.atan(Math.sqrt(Math.abs(d)))},Em:function(a,b,c){a=[a,b,c];b=[];for(c=0;3>c;++c){var d=a[c],e=_.Vb(d),d=_.Wb(d),f=b[c]=[];f[0]=Math.cos(e)*Math.cos(d);f[1]=Math.cos(e)*Math.sin(d);f[2]=Math.sin(e)}return 0<b[0][0]*b[1][1]*b[2][2]+b[1][0]*b[2][1]*b[0][2]+b[2][0]*b[0][1]*b[1][2]-b[0][0]*b[2][1]*b[1][2]-b[1][0]*b[0][1]*b[2][2]-b[2][0]*b[1][1]*b[0][2]?
1:-1}};var Aw={decodePath:function(a){for(var b=_.w(a),c=Array(Math.floor(a.length/2)),d=0,e=0,f=0,g=0;d<b;++g){var h=1,l=0,n;do n=a.charCodeAt(d++)-63-1,h+=n<<l,l+=5;while(31<=n);e+=h&1?~(h>>1):h>>1;h=1;l=0;do n=a.charCodeAt(d++)-63-1,h+=n<<l,l+=5;while(31<=n);f+=h&1?~(h>>1):h>>1;c[g]=new _.E(1E-5*e,1E-5*f,!0)}c.length=g;return c},encodePath:function(a){a instanceof _.yc&&(a=a.getArray());return Aw.co(a,function(a){return[Math.round(1E5*a.lat()),Math.round(1E5*a.lng())]})},co:function(a,b){for(var c=[],
d=[0,0],e,f=0,g=_.w(a);f<g;++f)e=b?b(a[f]):a[f],Aw.si(e[0]-d[0],c),Aw.si(e[1]-d[1],c),d=e;return c.join("")},si:function(a,b){return Aw.eo(0>a?~(a<<1):a<<1,b)},eo:function(a,b){for(;32<=a;)b.push(String.fromCharCode((32|a&31)+63)),a>>=5;b.push(String.fromCharCode(a+63));return b}};_.Mc.google.maps.geometry={encoding:Aw,spherical:zw,poly:yw};_.k=xw.prototype;_.k.decodePath=Aw.decodePath;_.k.encodePath=Aw.encodePath;_.k.computeDistanceBetween=zw.computeDistanceBetween;_.k.interpolate=zw.interpolate;_.k.computeHeading=zw.computeHeading;_.k.computeOffset=zw.computeOffset;_.k.computeOffsetOrigin=zw.computeOffsetOrigin;_.mc("geometry",new xw);});
