




/*
     FILE ARCHIVED ON 18:18:32 oct. 18, 2016 AND RETRIEVED FROM THE
     INTERNET ARCHIVE ON 0:03:12 nov. 25, 2016.
     JAVASCRIPT APPENDED BY WAYBACK MACHINE, COPYRIGHT INTERNET ARCHIVE.

     ALL OTHER CONTENT MAY ALSO BE PROTECTED BY COPYRIGHT (17 U.S.C.
     SECTION 108(a)(3)).
*/
google.maps.__gjsload__('poly', function(_){'use strict';var DW=function(a){for(a=a.toString(16);2>a.length;)a="0"+a;return a},EW=function(a){var b=new _.LI(["mousemove","mouseup","mousewheel"]);_.KA(b,["offset","panes","projectionTopLeft","size"],a);return b},FW=function(a,b,c){var d=a.path;a=a.b;for(var e=[],f=a?[]:null,g=d[0]==d[d.length-2]&&d[1]==d[d.length-1],h=0,l=d.length-2;h<l;h+=2){var n=d[h],q=d[h+1],r=d[h+2],u=d[h+3],x,A;a&&(x=a[h/2],A=a[h/2+1]);var C,D;switch(b){case 0:C=n>=c;D=r>=c;break;case 1:C=n<=c;D=r<=c;break;case 2:C=q>=
c;D=u>=c;break;case 3:C=q<=c,D=u<=c}!h&&C&&(e.push(n,q),a&&f.push(x));if(C!=D){var H;switch(b){case 0:case 1:H=(c-n)/(r-n);e.push(c,q+H*(u-q));break;case 2:case 3:H=(c-q)/(u-q),e.push(n+H*(r-n),c)}a&&f.push(x+H*(A-x))}D&&(e.push(r,u),a&&f.push(A))}g&&e.length&&(e[0]!=e[e.length-2]||e[1]!=e[e.length-1])&&(e.push(e[0],e[1]),a&&f.push(a[a.length-1]));return{path:e,b:f}},GW=_.na(),HW=function(a){var b=EW(a);_.z.addListener(b,"mousemove",_.lb);_.z.addListener(b,"mouseup",_.lb);_.z.addListener(b,"mousewheel",
function(b){var c=a.get("mouseEventTarget");c&&_.z.trigger.apply(null,[c,"mousewheel"].concat(_.Va(arguments,0)))});return b},IW=function(a,b,c,d){for(var e=null,f=c*c,g=0,h=d.length;g<h;++g){var l;l=a;var n=b,q=c,r=d[g],u=r.length;if(!u||0>=q)l=null;else{var x=0,A=q*q*1.01,C=[0,0],D,H,K,G,O,X;G=r[x++]-l;O=r[x++]-n;X=(G<-q?1:0)|(G>q?2:0)|(O<-q?4:0)|(O>q?8:0);var fa=G*G+O*O;!X&&fa<=A&&(A=fa,C[0]=G,C[1]=O);for(;x<u;)if(D=G,H=O,K=X,G=r[x++]-l,O=r[x++]-n,X=(G<-q?1:0)|(G>q?2:0)|(O<-q?4:0)|(O>q?8:0),!(K&
X)){fa=G*G+O*O;!X&&fa<=A&&(A=fa,C[0]=G,C[1]=O);K=G-D;var Fa=O-H,Ea=K*K+Fa*Fa;if(!(1E-12>Ea)){var Jb=G*K+O*Fa;0>Jb||Jb>Ea||(fa-=Jb*Jb/Ea,fa<=A&&(A=fa,Ea=1-Jb/Ea,C[0]=D+K*Ea,C[1]=H+Fa*Ea))}}C[0]+=l;C[1]+=n;C[2]=A;l=A<=q*q?C:null}l&&l[2]<=f&&(f=l[2],e=l)}return e},JW=function(a,b,c){for(var d=0,e=0,f=c.length;e<f;++e)d+=_.dG(a,b,c[e]);return!!(d&1)},KW=function(a,b){for(var c=new _.E(0,0),d=new _.I(0,0),e=0,f=a.length;e<f;e+=2)_.E.call(c,a[e],a[e+1],!0),d=b.fromLatLngToPoint(c,d),a[e]=d.x,a[e+1]=d.y},
LW=function(a){var b=a.length;!b||a[0]==a[b-2]&&a[1]==a[b-1]||(a.push(a[0]),a.push(a[1]))},NW=function(){var a=new _.ug({clickable:!1,fillOpacity:0});a.bindTo("map",this);a.bindTo("strokeColor",this);a.bindTo("strokeOpacity",this);a.bindTo("strokeWeight",this);var b=["center","freeVertexPosition","freeVertexIsCenter"],c=new _.eu(b,"return",MW);_.KA(c,b,this);a.bindTo("center",c,"return");b=["center","radius","planetRadius","freeVertexPosition","freeVertexIsCenter"];c=new _.eu(b,"return",(0,_.p)(this.f,
this));_.KA(c,b,this);a.bindTo("radius",c,"return");this.b=_.MI();this.b.bindTo("zIndex",this);a.bindTo("zIndex",this.b,"ghostZIndex")},MW=function(a,b,c){return c&&b||a},RW=function(a,b,c,d,e,f,g,h){var l=this,n=_.Y("div",a);a=9+2*(1+c);_.zf(n,new _.J(a,a));g.construct(n,c,9,1,h?.5:1);var q=new _.aG(f);q.bindTo("position",l);f=new _.PF(n);f.bindTo("position",q,"rawPosition");f.bindTo("containerPixelBounds",l,"mapPixelBounds");f.bindTo("panningEnabled",l);f.set("draggableCursor",d);this.b=n;this.m=
b;this.B=c;this.F=q;this.C=e;this.j=f;this.l=!1;this.f={};var r;this.R=[_.z.addListener(f,"dragstart",function(){q.set("referencePosition",l.get("position"));q.set("snappingCallback",l.C);l.f.mouseout=!0;l.f.mouseover=!0;r=[_.z.forward(b,"mousemove",n),_.z.forward(b,"mouseup",n)];b.set("draggableCursor",d);b.set("active",!0)}),_.z.addListener(f,"dragend",function(){q.set("referencePosition",null);q.set("snappingCallback",null);q.set("rawPosition",q.get("position"));b.set("active",!1);r&&(_.v(r,_.z.removeListener),
r=null)}),_.z.forward(f,"panbynow",l),_.z.forward(f,"dragstart",l),_.z.forward(f,"dragend",l),_.z.addListener(f,"mouseover",function(){l.l=!0;OW(l)}),_.z.addListener(f,"mouseout",function(){l.l=!1;OW(l)})];_.v(PW,function(a){l.R.push(QW(l,a))})},QW=function(a,b){function c(a){d.f[b]?d.f[b]=!1:(_.nb(a),_.ob(a),_.z.trigger(d,b,a))}var d=a;return"rightclick"==b?_.z.addDomListener(d.b,"contextmenu",c):_.z.addListener(d.j,b,c)},OW=function(a){var b;if(a.l){var c=_.kJ(a.get("color"));c&&(c.j=Math.floor((c.j+
255)/2),c.f=Math.floor((c.f+255)/2),c.b=Math.floor((c.b+255)/2),b=["#",DW(c.j),DW(c.f),DW(c.b)].join(""))}a.b.firstChild.style.backgroundColor=b||"white"},YW=function(a,b,c,d,e,f){function g(){h.l||_.z.trigger(h,"toolbar",{cb:!1})}this.M=a;this.C=b;this.B=c;this.f=_.Y("div",e,_.Yg);this.l=d;this.H=f;this.b=[];a.forEach((0,_.p)(this.m,this));var h=this;this.F=[_.z.addListener(a,"insert_at",function(b){h.m(a.getAt(b),b);XW(h,b+1);g()}),_.z.addListener(a,"remove_at",function(a){var b=h.b[a];h.b.splice(a,
1);h.G(b);XW(h,a);g()}),_.z.addListener(a,"set_at",function(b){h.b[b].Lc.set("latLngPosition",a.getAt(b));g()})]},XW=function(a,b){for(var c=a.b.length;b<c;++b)a.b[b].index=b},ZW=function(a,b){this.l=a;this.m=b;this.j=null;this.f=!1;this.b=new _.yc;_.z.bind(this.b,"set_at",this,this.vp)},bX=function(a){var b=a.get("panes");if(!b)return null;b=new YW(a.b,$W,aX,!1,b.overlayMouseTarget,a.m);b.bindTo("projection",a);b.bindTo("zoom",a);b.bindTo("projectionCenterQ",a);b.bindTo("panningEnabled",a);b.bindTo("mapPixelBounds",
a);b.bindTo("color",a);b.bindTo("zIndex",a);b.bindTo("offset",a);var c=a.l;c.bindTo("freeVertexPosition",b);var d,e;_.z.addListener(b,"dragstart",function(b){d=a.get("center");e=a.get("radius");c.set("freeVertexIsCenter",0==b);c.set("map",a.get("map"))});_.z.addListener(b,"dragend",function(b,g){c.set("map",null);_.z.trigger(a,"toolbar",{cb:!0,position:g,action:function(){a.set("center",d);a.set("radius",e)}})});_.z.forward(b,"dragstart",a);_.z.forward(b,"dragend",a);_.z.forward(b,"panbynow",a);return b},
cX=function(a){var b=a.j;b&&(b.unbindAll(),b.release(),_.z.clearInstanceListeners(b),a.j=null)},dX=_.na(),gX=function(a,b,c){function d(){a.get("editable")?eX(a,b,c):(fX(a),_.z.trigger(a,"toolbar",{cb:!1}))}a.editable_changed=d;d()},eX=function(a,b,c){if(!a.j){var d=new _.QI(a,!0);a.l=d;var e=new NW;e.bindTo("strokeColor",d);e.bindTo("strokeOpacity",d,"ghostStrokeOpacity");e.bindTo("strokeWeight",d);e.bindTo("center",a);e.bindTo("radius",a);e.bindTo("planetRadius",c);e.bindTo("zIndex",a);a.m=e;var f=
b.__gm;a.b=HW(f);var g=_.cG(f,a),h=_.cl()?9:0,l=new dX,e=new ZW(e,function(b,c,d,e){return new RW(b,a.b||null,h,c,g,d,l,e)});e.set("map",b);e.bindTo("center",a);e.bindTo("radius",a);e.bindTo("planetRadius",c);e.bindTo("panes",f);e.bindTo("projection",b);e.bindTo("zoom",f);e.bindTo("projectionCenterQ",f);e.bindTo("panningEnabled",b,"draggable");e.bindTo("mapPixelBounds",f,"pixelBounds");e.bindTo("offset",f);e.bindTo("color",d,"strokeColor");e.bindTo("zIndex",a);a.j=e;_.z.addListener(e,"dragstart",
function(){a.set("capturing",!0)});_.z.addListener(e,"dragend",function(){a.set("capturing",!1)});_.z.forward(e,"panbynow",f);_.z.forward(e,"toolbar",a)}},fX=function(a){var b=a.j;b&&(b.unbindAll(),b.set("map",null),_.z.clearInstanceListeners(b),delete a.j,a.b.release(),delete a.b,a.set("capturing",!1),a.m.unbindAll(),delete a.m,a.l.release(),delete a.l)},hX=function(a,b,c,d,e,f){this.j=a;this.ea=c;a=a.get("center");b=c.fromDivPixelToLatLng(b);this.m=d(a,b);this.f=_.Wy(b,a);this.l=f},iX=function(){var a=
this;_.yf.call(a);var b=this.b=new _.Ce;b.j=!0;b.bindTo("capturing",a);b.bindTo("cursor",a);b.bindTo("map",a);b.bindTo("strokeColor",a);b.bindTo("strokeOpacity",a);b.bindTo("strokeWeight",a);b.bindTo("strokePosition",a);b.bindTo("fillColor",a);b.bindTo("fillOpacity",a);b.bindTo("clickable",a);b.bindTo("zIndex",a);b.bindTo("suppressUndo",a);var c=this.f=[];_.v(PW,function(d){c.push(_.z.forward(b,d,a))});c.push(_.z.forward(a,"toolbar",b))},jX=function(a,b){var c=Array(250),d=[c],e=_.Sb(a.lat()),f=_.Sb(a.lng()),
g=Math.cos(b),h=Math.sin(b),l=Math.cos(e),n=Math.sin(e);if(1E-6<l)for(a=0;250>a;++a){var q=a/250*Math.PI*4,q=q+Math.sin(q+Math.PI),r=q/2,u=n*g+l*h*Math.cos(r),q=Math.asin(u),r=f+Math.atan2(Math.sin(r)*h*l,g-n*u),r=_.$a(r,-Math.PI,Math.PI);c[a]=new _.E(_.Tb(q),_.Tb(r))}else for(f=_.Tb(b),f=0<a.lat()?a.lat()-f:a.lat()+f,a=0;250>a;++a)c[a]=new _.E(f,360*a/250);e-b<-Math.PI/2&&(b=[new _.E(-90,-200,!0),new _.E(90,-200,!0),new _.E(90,-100,!0),new _.E(90,0,!0),new _.E(90,100,!0),new _.E(90,200,!0),new _.E(-90,
200,!0),new _.E(-90,100,!0),new _.E(-90,0,!0),new _.E(-90,-100,!0),new _.E(-90,-200,!0)],d.push(b));return d},kX=function(a){this.y=this.x=0;this.z=a},mX=function(a){var b=Math.sqrt(lX(a,a));1E-12>b||(a.x/=b,a.y/=b,a.z/=b)},lX=function(a,b){return a.x*b.x+a.y*b.y+a.z*b.z},nX=function(a,b,c){c.x=a.y*b.z-a.z*b.y;c.y=a.z*b.x-a.x*b.z;c.z=a.x*b.y-a.y*b.x},oX=function(a,b){var c=_.Sb(a[0]);a=_.Sb(a[1]);var d=Math.cos(c);b.x=Math.cos(a)*d;b.y=Math.sin(a)*d;b.z=Math.sin(c)},pX=function(a,b){var c=Math.atan2(a.y,
a.x);b[0]=_.Tb(Math.atan2(a.z,Math.sqrt(a.x*a.x+a.y*a.y)));b[1]=_.Tb(c)},qX=function(a,b,c){c.x=a.x+b.x;c.y=a.y+b.y;c.z=a.z+b.z;mX(c)},sX=function(a,b,c,d,e,f){this.f=a;this.ea=c;this.C=e;this.B=f;var g=rX(this);b=c.fromDivPixelToLatLng(b);this.F=_.Wy(g,b);this.G=d(g,b);var h=this.m=[];a.get("latLngs").forEach(function(a){var b=[];a.forEach(function(a){b.push({heading:d(g,a),ec:_.Wy(a,g)})});h.push(b)});this.j=g;this.l=b.lng()-g.lng()},rX=function(a){a=a.f.get("latLngs");var b=new kX(0),c=new kX(0);
a.forEach(function(a){a.forEach(function(a){oX([a.lat(),a.lng()],c);b.x+=c.x;b.y+=c.y;b.z+=c.z})});mX(b);a=[0,0];pX(b,a);a[0]=_.Za(a[0],-89,89);return new _.E(a[0],a[1])},tX=function(a,b,c,d,e){_.sk.call(this,a,b);_.m(c)&&(this.path=c);_.m(d)&&(this.vertex=d);_.m(e)&&(this.edge=e)},uX=function(a,b,c){this.j=a;this.ea=c;this.f=c.fromDivPixelToLatLng(b);var d=this.l=[];a.get("latLngs").forEach(function(a){d.push(_.Va(a.getArray(),0))})},xX=function(a,b){this.C=a;this.f=_.Y("div",null,null,vX);this.f.style.backgroundColor=
"red";_.am(this.f,.01);a=this.j=new _.PF(this.f);a.bindTo("position",this);a.bindTo("containerPixelBounds",this);a.bindTo("panningEnabled",this);a.set("draggableCursor","pointer");a.set("draggingCursor","pointer");a.set("size",vX);a.set("anchorPoint",wX);this.B=[_.z.bind(a,"dragstart",this,this.Dg),_.z.bind(a,"dragend",this,this.af),_.z.bind(a,"click",this,this.dk),_.z.bind(a,"mousedown",this,this.hk),_.z.bind(a,"mousemove",this,this.ik),_.z.bind(a,"mouseup",this,this.jk),_.z.forward(a,"panbynow",
this)];_.cl()&&(b=b.__gm,_.z.bind(b,"movestart",this,this.fk),_.z.bind(b,"move",this,this.gk),_.z.bind(b,"moveend",this,this.ek));b=new _.eu(["mousedown","dragging"],"active",function(a,b){return a||b});b.bindTo("dragging",this,null,!0);b.bindTo("mousedown",this,null,!0);this.bindTo("active",b,null,!0)},yX=function(a,b){b=b?1E9:(a.b.get("zIndex")||0)-2;_.Yl(a.f,b)},zX=function(a,b,c){var d=a.get("position"),d=a.ea.fromDivPixelToLatLng(d);_.z.trigger(a.b,b,new _.sk(d,c))},AX=function(a,b){var c=a.__gm;
b.bindTo("panningEnabled",a,"draggable");b.bindTo("panes",c);b.bindTo("projectionController",c);b.bindTo("containerPixelBounds",c,"pixelBounds");c.ma=_.z.forward(b,"panbynow",c)},BX=function(a,b){function c(){var b=a.getMap();a.getDraggable()&&(_.Tm(b,"Od"),_.Vm("Od","-p",a,!(!b||!b.b)))}a.draggable_changed=c;c();a.G=[_.z.addListener(a,"mouseover",function(c){null==c.vertex&&null==c.edge&&b.set("poly",a)}),_.z.addListener(a,"click",function(b){null==b.vertex&&null==b.edge&&a.getDraggable()&&(b=a.getMap(),
_.Vm("Od","-i",a,!(!b||!b.b)))}),_.z.addListener(a,"mouseout",function(a){null!=a.vertex||null!=a.edge||_.Zi(a.xa)||b.set("poly",null)})]},CX=function(a){var b=a.__gm.l;b.b||(_.F("geometry",function(c){var d=new xX(function(a,b,d){return new hX(a,b,d,c.computeHeading,0,c.computeOffsetOrigin)},a);AX(a,d);b.b=function(b){BX(b,d);var c=b.eq=new _.eu(["baseMapType"],"planetRadius",_.we);c.bindTo("baseMapType",a.__gm);var e=b.kh=new iX;e.set("map",a);e.bindTo("radius",b);e.bindTo("center",b);e.bindTo("capturing",
b);e.bindTo("clickable",b);e.bindTo("cursor",b);e.bindTo("fillColor",b);e.bindTo("fillOpacity",b);e.bindTo("strokeColor",b);e.bindTo("strokeOpacity",b);e.bindTo("strokeWeight",b);e.bindTo("strokePosition",b);e.bindTo("zIndex",b);e.bindTo("suppressUndo",b);e.bindTo("planetRadius",c);b.ba=[];_.v(PW,function(a){b.ba.push(_.z.forward(e,a,b))});b.ba.push(_.z.forward(b,"toolbar",e));gX(b,a,c);_.Tm(a,"Oc");_.Vm("Oc","-p",b,!(!a||!a.b));_.z.addListener(b,"click",function(){_.Vm("Oc","-i",b,!(!a||!a.b))})}}),
b.onRemove=function(a){var b=a.kh;b.unbindAll();b.set("map",null);b.release();delete a.kh;_.v(a.ba,_.z.removeListener);delete a.ba;delete a.editable_changed;fX(a);_.Wm("Oc","-p",a)})},DX=function(a,b,c,d){a.capturing_changed=function(){if(a.get("capturing"))if(0==a.get("clickable")){var e=a.f=new GW;e.bindTo("draggableCursor",a,"cursor");e.set("active",!0);b.bindTo("cursor",e);d.Ab(e)}else d.Gd(c,a);else a.f?(d.Hd(a.f),a.f.unbindAll(),b.unbind("cursor"),b.set("cursor",""),delete a.f):d.Fd(c,a)}},
JX=function(a,b,c){var d=this;this.C=a;this.l=b;this.m=c;this.f={};this.b={};this.j=0;this.B=function(a){EX(d,this,a)};a.b=function(a){var b=d.get("projection"),b=a.De={style:FX(d.m,a),jc:GX(a,b)};HX(d,a);a.changed=d.B;_.Ac(d.l,b)};a.onRemove=function(a){var b=a.De;delete a.De;d.l.remove(b);delete a.changed;IX(a);a=_.yb(a);delete d.f[a];delete d.b[a]}},EX=function(a,b,c){var d=_.yb(b);c in KX&&(a.b[d]=b,IX(b));c in LX&&(a.f[d]=b);MX(a)},MX=function(a){a.j||(a.j=_.hb(function(){a.j=0;var b=a.f;a.f=
{};var c=a.b;a.b={};for(var d in b){var e=b[d],f=e.De;f.style=FX(a.m,e);f.Yf&&!c[d]&&f.Yf()}var b=a.l,g=a.get("projection");for(d in c)e=c[d],f=e.De,b.remove(f),f.jc=GX(e,g),_.Ac(b,f),HX(a,e)}))},HX=function(a,b){function c(){EX(e,b,"latLngs")}var d=b.get("latLngs");if(d){var e=a,f=_.yb(b);a=d.getArray();for(var g=0,h=a.length;g<h;++g){var l=a[g];NX(l);l.f.Ka[f]=l.l.Ka[f]=l.j.Ka[f]=c}NX(d);d.l.Ka[f]=d.j.Ka[f]=function(a,b){OX(b,f);c()};d.f.Ka[f]=c}},IX=function(a){var b=a.get("latLngs");if(b){a=_.yb(a);
OX(b,a);for(var b=b.getArray(),c=0,d=b.length;c<d;++c)OX(b[c],a)}},NX=function(a){a.f||(a.f=function(b){_.Wa(a.f.Ka,function(a,d){d(b)})},a.f.Ka={});a.l||(a.l=function(b,c){_.Wa(a.l.Ka,function(a,e){e(b,c)})},a.l.Ka={});a.j||(a.j=function(b,c){_.Wa(a.j.Ka,function(a,e){e(b,c)})},a.j.Ka={})},OX=function(a,b){a.f&&delete a.f.Ka[b];a.l&&delete a.l.Ka[b];a.j&&delete a.j.Ka[b]},UX=function(){var a=this.f=_.Y("div");_.Yl(a,-202);_.Xl(a,"pointer");_.kA(a);this.b=_.aA(PX,a,QX,RX);_.z.bind(this,"toolbar",
this,this.kk);_.z.W(a,"click",this,this.Zn);_.z.addDomListener(a,"mouseover",(0,_.p)(this.Ee,this,SX));_.z.addDomListener(a,"mouseout",(0,_.p)(this.Ee,this,QX));_.z.W(a,"mousedown",this,function(a){_.ob(a);this.Ee(TX)});_.z.addDomListener(a,"mousemove",_.ob);_.z.addDomListener(a,"mouseup",_.ob)},VX=function(a){a.j&&_.z.clearListeners(a.j,"suppressundo_changed")},XX=function(a,b,c,d){a.Ee(QX);_.ol(a.f,new _.I(b.x+WX.x,b.y+WX.y));a.l=c;VX(a);a.j=d;_.Ul(a.f);_.z.addListener(d,"suppressundo_changed",
function(){d.get("suppressUndo")&&a.wc()})},YX=function(a){var b=this;this.b=a;_.z.addListener(a,"set_at",function(c){_.z.trigger(b,"set_at",c);var d=a.getLength();0==c&&1<d&&_.z.trigger(b,"set_at",d)});_.z.addListener(a,"insert_at",function(c){_.z.trigger(b,"insert_at",c);var d=a.getLength();2==d?_.z.trigger(b,"insert_at",2):0==c&&1<d&&_.z.trigger(b,"set_at",d)});_.z.addListener(a,"remove_at",function(c){_.z.trigger(b,"remove_at",c);var d=a.getLength();1==d?_.z.trigger(b,"remove_at",1):0==c&&1<d&&
_.z.trigger(b,"set_at",d)})},ZX=function(a,b,c){this.f=a;this.j=b;this.b=c;this.R=[_.z.bind(a,"set_at",this,this.zj),_.z.bind(a,"insert_at",this,this.vg),_.z.bind(a,"remove_at",this,this.yj)];b=0;for(a=a.getLength();b<a;++b)this.vg(b)},aY=function(a,b,c){var d=a.get("projection");if(d){var e=a.f,f=e.getAt(c),g=a.j,h=a.get("geodesic");0<c&&g.setAt(c-1,$X(e.getAt(c-1),f,h,d,a.b));c<e.getLength()-1&&(a=$X(f,e.getAt(c+1),h,d,a.b),b?g.insertAt(c,a):g.setAt(c,a))}},$X=function(a,b,c,d,e){c?d=e(a,b,.5):
(180<Math.abs(a.lng()-b.lng())&&(a=new _.E(a.lat(),_.$a(a.lng(),b.lng()-180,b.lng()+180),!0)),a=d.fromLatLngToPoint(a),b=d.fromLatLngToPoint(b),d=d.fromPointToLatLng(new _.I((a.x+b.x)/2,(a.y+b.y)/2)));return d},bY=function(a,b,c,d){this.m=a;this.l=b;this.F=c;this.C=d;this.f=[];this.b=[];this.B=[]},dY=function(a,b,c){var d=cY(a,b,c,!1),e=a.m,f;_.z.addListener(d,"dragstart",function(c){f=b.getAt(c);var g=b.getArray(),l=a.l,n=g.length;if(2>n)e.set("anchors",[]);else{var q=g[l&&0==c?n-1:c-1];c=g[l&&c==
n-1?0:c+1];g=[];q&&g.push(q);c&&g.push(c);e.set("anchors",g)}e.bindTo("freeVertexPosition",d);e.set("map",a.get("map"))});_.z.addListener(d,"dragend",function(c,d){e.set("map",null);_.z.trigger(a,"toolbar",{cb:!0,position:d,action:function(){b.setAt(c,f)}})});return d},eY=function(a,b,c){var d=new _.yc,e=a.l?new YX(b):b,f=new ZX(e,d,a.C);f.bindTo("geodesic",a);f.bindTo("projection",a);var g=cY(a,d,c,!0);g.j=f;var h=a.m;_.z.addListener(g,"dragstart",function(b){b=[e.getAt(b),e.getAt(b+1)];h.set("anchors",
b);h.bindTo("freeVertexPosition",g);h.set("map",a.get("map"))});_.z.addListener(g,"dragend",function(c,e){b.insertAt(c+1,d.getAt(c));h.set("map",null);_.z.trigger(a,"toolbar",{cb:!0,position:e,action:function(){b.removeAt(c+1)}})});return g},cY=function(a,b,c,d){var e=new YW(b,["pointer"],[0],d,c,a.F);e.bindTo("projection",a);e.bindTo("zoom",a);e.bindTo("projectionCenterQ",a);e.bindTo("panningEnabled",a);e.bindTo("mapPixelBounds",a);e.bindTo("color",a);e.bindTo("zIndex",a);e.bindTo("offset",a);_.z.forward(e,
"dragstart",a);_.z.forward(e,"dragend",a);_.z.forward(e,"panbynow",a);_.z.forward(e,"toolbar",a);_.v(PW,function(c){_.z.addListener(e,c,function(f){var g=b.getAt(f),l;if(a.l)for(var n=d?a.b:a.f,q=0;q<n.length;++q)if(n[q]==e){l=q;break}_.z.trigger(a,c,new tX(g,void 0,l,d?void 0:f,d?f:void 0))})});return e},fY=function(a){var b=(0,_.p)(a.j,a);_.v(a.f,b);_.v(a.b,b);a.f.length=0;a.b.length=0;_.v(a.B,_.z.removeListener);a.B.length=0},jY=function(a,b,c){function d(){g[A++]=l.ca[0];g[A++]=l.ca[1];f&&(h[r++]=
l.ec);n=l}var e=a.path,f=a.b;if(!e.length)return a;var g=Array(e.length),h=f?Array(f.length):null;a=[];var l,n=gY();g[0]=n.ca[0]=e[0];g[1]=n.ca[1]=e[1];f&&(h[0]=n.ec=f[0]);n.depth=0;oX(n.ca,n.Mc);for(var q=1,r=1,u=[],x=2,A=2;x<e.length||u.length;)if(u.length?l=u.pop():(l=gY(),l.depth=0,l.ca[0]=e[x++],l.ca[1]=e[x++],f&&(l.ec=f[q++]),oX(l.ca,l.Mc)),12<=Math.max(n.depth,l.depth))d();else{var C=new _.uf;C.J=Math.min(n.ca[0],l.ca[0]);C.N=Math.max(n.ca[0],l.ca[0]);C.K=Math.min(n.ca[1],l.ca[1]);C.O=Math.max(n.ca[1],
l.ca[1]);if(_.Fk(b,C)){var D=gY();qX(n.Mc,l.Mc,D.Mc);pX(D.Mc,D.ca);D.depth=Math.max(n.depth,l.depth)+1;f&&(D.ec=(n.ec+l.ec)/2);var H=C.K-1E-6,K=C.O+1E-6,C=D.ca;C[1]=hY(H,K,C[1]);iY(n.ca,l.ca,a);Math.max(Math.abs(D.ca[0]-a[0]),Math.abs(D.ca[1]-a[1]))<=c?d():(u.push(l),u.push(D))}else d()}return{path:g,b:h}},iY=function(a,b,c){c[0]=(a[0]+b[0])/2;c[1]=(a[1]+b[1])/2},hY=function(a,b,c){for(;c<a;)c+=360;for(;c>b;)c-=360;return c},gY=function(){return{ca:[0,0],Mc:new kX(0)}},lY=function(a){var b=["px",
"%"];if(!a||!_.w(b))return null;if("0"==a)return{value:0,Uc:b[0]};for(var c=0,d=b.length;c<d;++c){var e=b[c],f=(kY[e]=kY[e]||new RegExp("^(\\d+(?:\\.\\d+)?)"+e+"$")).exec(a);if(f)return{value:(0,window.parseFloat)(f[1]),Uc:e}}return null},mY=function(a){return function(b,c){if("px"==b.Uc)b=b.value/a;else{var d=_.w(c);b=d?b.value/100*c[d-1]:0}return b}},nY=function(a,b,c,d){--b;if(!(0>b)){var e=a.length,f=0;for(d(0);f<b;){var g=1<<e,h=e?a[e-1][f/g]:0,l=f+g;l>=b&&(l=b);e&&c(f,l,h)?--e:(d(l),f=l,f&g||
++e)}}},oY=function(a,b){return function(c,d){if(0==c)return!0;c=a[c];d=a[d];for(var e=0,f;f=b[e];++e){var g=f.offset;if(f=f.repeat){if(Math.floor((c-g)/f)!=Math.floor((d-g)/f))return!0}else if(c<g&&g<=d)return!0}return!1}},pY=function(a,b,c,d){var e=a.J,f=a.K,g=a.N,h=a.O;return function(a,n,q){var l=d[2*a],u=d[2*a+1];a=d[2*n];n=d[2*n+1];var x=Math.min(u,n)-q,A=Math.max(l,a)+q,C=Math.max(u,n)+q;Math.min(l,a)-q<=g&&e<=A&&x<=h&&f<=C?q>b?q=!0:(x=c.fromLatLngToPoint(new _.E(l,u,!0)),A=c.fromLatLngToPoint(new _.E(a,
n,!0)),x=c.fromPointToLatLng(new _.I((x.x+A.x)/2,(x.y+A.y)/2),!0),u=(u+n)/2,l=(l+a)/2-x.lat(),a=u-x.lng(),q=Math.sqrt(l*l+a*a)+q>b):q=!1;return q}},qY=function(a,b,c){return function(d,e,f){var g=d.path,h=d.b,l=pY(a,b,c,g);d=l;if(h){var n=oY(h,f);d=function(a,b,c){return l(a,b,c)||n(a,b)}}var q=[],r=h?[]:null;nY(e,g.length/2,d,function(a){q.push(g[2*a],g[2*a+1]);h&&r.push(h[a])});return{path:q,b:r}}},rY=function(a,b){var c=0;_.ab(a,-16,.001)&&(c|=1);_.ab(a,272,.001)&&(c|=2);_.ab(b,-16,.001)&&(c|=
4);_.ab(b,272,.001)&&(c|=8);return c},sY=function(a,b,c){var d=a.fromPointToLatLng(c);a=a.fromPointToLatLng(new _.I(c.x+b,c.y+b));return Math.min(Math.abs(d.lat()-a.lat()),Math.abs(d.lng()-a.lng()))},tY=function(a,b,c){b=this.B=1<<b;this.m=c;var d=_.vf((256*a.x-16)/b,(256*a.y-16)/b,(256*(a.x+1)+16)/b,(256*(a.y+1)+16)/b);a=new _.I(d.J,d.K);var d=new _.I(d.N,d.O),e=c.fromPointToLatLng(a,!0),f=c.fromPointToLatLng(d,!0),g=Math.min(e.lat(),f.lat()),h=Math.max(e.lat(),f.lat()),l=Math.min(e.lng(),f.lng()),
e=Math.max(e.lng(),f.lng()),f=(l+e)/2,n=_.$a(f,-180,180),l=l+(n-f),e=e+(n-f),f=_.vf(g,l,h,e),g=new _.E(g,l,!0);c.fromLatLngToPoint(g,a);h=new _.E(h,e,!0);c.fromLatLngToPoint(h,d);d=new _.uf([a,d]);this.f=f;this.b=d;a=.5/b;d=this.b;this.l=Math.min(sY(c,a,new _.I(d.J,d.K)),sY(c,a,new _.I(d.N,d.O)));this.C=qY(this.f,this.l,c);this.j=mY(b)},uY=function(a,b,c){this.j=a;this.f=b;this.l=c},vY=function(a){return _.bb(a,function(a){return _.bb(a,function(a){return Math.round(a)})})},yY=function(a,b,c,d){function e(){a.get("editable")?
(wY(a,b,d),_.Tm(b,"Oe"),_.Vm("Oe","-p",a,!(!b||!b.b))):(_.z.trigger(c,"toolbar",{cb:!1,Fb:a}),xY(a))}a.editable_changed=e;e();a.B=_.z.addListener(a,"toolbar",function(b){b.Fb=a;_.z.trigger(c,"toolbar",b)})},wY=function(a,b,c){if(!a.m){var d=new _.QI(a,a.Fa);a.C=d;var e=new _.NI;e.bindTo("strokeColor",d);e.bindTo("strokeOpacity",d,"ghostStrokeOpacity");e.bindTo("strokeWeight",d);e.bindTo("geodesic",a);e.bindTo("zIndex",a);a.Eb=e;var f=b.__gm;a.b=HW(f);var g=_.cG(f,a),h=_.cl()?9:0,l=new dX,n=new bY(e,
a.Fa,function(b,c,d,e){return new RW(b,a.b||null,h,c,g,d,l,e)},c);n.set("map",b);n.bindTo("paths",a,"latLngs");n.bindTo("panes",f);n.bindTo("projection",b);n.bindTo("zoom",f);n.bindTo("projectionCenterQ",f);n.bindTo("panningEnabled",b,"draggable");n.bindTo("mapPixelBounds",f,"pixelBounds");n.bindTo("offset",f);n.bindTo("color",d,"strokeColor");n.bindTo("zIndex",a);n.bindTo("geodesic",a);n.bindTo("suppressGhostControlPoints",a);a.m=n;a.F=[_.z.addListener(a,"mousedown",function(){a.set("capturing",
!0)}),_.z.addListener(a,"mouseup",function(){a.set("capturing",!1)})];_.z.addListener(a,"click",function(){a.get("editable")&&_.Vm("Oe","-i",a,!(!b||!b.b))});_.z.forward(n,"panbynow",f);_.z.forward(n,"toolbar",a);_.v(PW,function(b){_.z.forward(n,b,a)})}},xY=function(a){var b=a.m;b&&(b.unbindAll(),b.set("map",null),_.z.clearInstanceListeners(b),delete a.m,a.b.unbindAll(),a.b.release(),delete a.b,a.set("capturing",!1),_.v(a.F||[],_.z.removeListener),delete a.F,a.Eb.unbindAll(),delete a.Eb,a.C.release(),
delete a.C)},zY=function(a,b){this.b=a;this.f=_.Sk(b,Math.min(2,_.Bk()));this.tileSize=new _.J(256,256)},CY=function(a,b,c,d){this.B=c;this.l=a;a=_.nl(a);this.b=AY(a,b,d);_.ol(this.b,_.Yg);this.m=BY(this.b,d);this.C=AY(a,b,d);this.F=BY(this.C,d);this.H=new _.gG(this.m);this.G=new _.gG(this.F);this.f={};this.j=0},AY=function(a,b,c){a=a.createElement("canvas");a.width=b.width*c;a.height=b.height*c;a.style.width=_.V(b.width);a.style.height=_.V(b.height);_.$l(a);return a},BY=function(a,b){a=a.context=
a.getContext("2d");a.scale(b,b);a.lineCap=a.lineJoin="round";return a},FY=function(a){a.j||(a.j=_.hb(function(){a.j=0;var b=DY(a);if(b.length){a.b.parentNode||a.l.appendChild(a.b);var c=a.m,d=a.F;c.clearRect(0,0,256,256);for(var e=0,f;f=b[e];++e){var g=f.f,h=g.B;_.ab(1,h)?(a.B(c,f.b,g.strokeColor,g.f,g.b,g.l,g.fillColor,g.j),EY(f.l,g.m,c,a.H,1)):(d.clearRect(0,0,256,256),a.B(d,f.b,g.strokeColor,g.f/h,g.b,g.l),EY(f.l,g.m,d,a.G,h),c.globalAlpha=h,c.drawImage(a.C,0,0,256,256))}}else a.b.parentNode&&
a.l.removeChild(a.b)}))},EY=function(a,b,c,d,e){for(var f=0,g=a.length;f<g;++f){var h=b[f],l=c,n=d,q=a[f],r=h.l,u=h.scale,x=h.rotation,A=h.m,C=h.strokeColor,D=h.f/e,H=h.b,K=h.fillColor,h=h.j/e;l.beginPath();for(var G=0,O=q.length;G<O;G+=3)n.Ge(r,q[G],q[G+1],x+(A?q[G+2]:0),u);h&&(l.fillStyle=K,l.globalAlpha=h,l.fill());H&&(l.lineWidth=H,l.strokeStyle=C,l.globalAlpha=D,l.stroke())}},DY=function(a){var b=[];a=a.f;for(var c in a)b.push(a[c]);b.sort(function(a,b){return a.zIndex-b.zIndex});return b},GY=
function(a,b){function c(a,b){a.beginPath();for(var c=0,d;d=b[c];++c)if(d.length){a.moveTo(Math.round(d[0]),Math.round(d[1]));for(var e=2,f=d.length;e<f;)a.lineTo(Math.round(d[e++]),Math.round(d[e++]))}}var d=a.createElement("canvas");d.width=d.height=256*b;var e=d.getContext("2d");e.lineCap=e.lineJoin="round";e.scale(b,b);var f=[function(a,b,c,d,e){a.lineWidth=e;a.strokeStyle=c;a.globalAlpha=d;a.stroke()},function(a,b,c,d,e){a.lineWidth=2*e;a.strokeStyle=c;a.globalAlpha=d;a.save();a.clip();a.stroke();
a.restore()},function(a,b,f,n,q){e.lineWidth=2*q;e.strokeStyle=f;e.globalCompositeOperation="source-over";e.clearRect(0,0,256,256);c(e,b);e.stroke();e.globalCompositeOperation="destination-out";e.fill();a.globalAlpha=n;a.drawImage(d,0,0,256,256)}];return function(a,b,d,e,q,r,u,x){c(a,b);x&&(a.fillStyle=u,a.globalAlpha=x,a.fill());if(q)f[r](a,b,d,e,q)}},HY=function(a,b,c){this.j=a;this.f=c;this.b=null},KY=function(a,b,c,d,e){var f=this;this.f=b;this.b=d;this.j=e;a.b=function(a){IY(f,a)};a.onRemove=
function(a){delete a.Yf;f.f.remove(a.ta);a=a.jc;var b=a.ga,c;for(c in b){var d=b[c],e=d.la,g=e.b;delete g.f[_.yb(d)];FY(g);delete e.ga[_.yb(d)]}a.ga={};c=a.Nb;_.Wm(c.Fa?"Op":"Ol","-v",c)};c.b=function(a){JY(f,a)};c.onRemove=function(a){f.b.remove(a.ta);var b=a.ga,c;for(c in b){var d=b[c],e=d.j;delete e.ga[_.yb(d)];d=e.Nb;_.Wm(d.Fa?"Op":"Ol","-v",d)}a.ga={}};a=a.f;for(var g in a)IY(f,a[g]);c=c.f;for(g in c)JY(f,c[g])},IY=function(a,b){b.Yf=function(){var a=b.jc.ga,c;for(c in a){var d=a[c];d.f=b.style;
d.zIndex=b.style.zIndex;FY(d.la.b)}};var c=b.jc,d=c.ta;d.Fb=b;b.ta=d;_.iG(a.f,d);for(var d=a.b.search(d),e=0,f=d.length;e<f;++e)LY(b,d[e].Gb||null);0<d.length&&(c=c.Nb,_.Vm(c.Fa?"Op":"Ol","-v",c,a.j))},JY=function(a,b){var c=b.ta;c.Gb=b;_.iG(a.b,c);for(var c=a.f.search(b.ta),d=0,e=c.length;d<e;++d)LY(c[d].Fb||null,b),_.Vm(c[d].Fb.jc.Nb.Fa?"Op":"Ol","-v",c[d].Fb.jc.Nb,a.j)},LY=function(a,b){for(var c=a.jc,d=b.f,e=c.j,f=c.f,g=c.b,h=[],l=[],n=0,q=g.length;n<q;++n)l.push([]);n=0;for(q=e.length;n<q;++n){var r=
e[n],u=r.f,x;x=d;var A=g,C=u.b,D=[];if(C)for(var H=0,K;K=A[H];++H)D.push({offset:x.j(K.offset,C),repeat:x.j(K.repeat,C)});x=D;u=r.b?d.C(u,r.b,x):{path:_.Va(u.path,0),b:u.b};if(u.path.length&&(f&&(u=jY(u,d.f,d.l)),KW(u.path,d.m),r=d.b,u=FW(u,0,r.J),u=FW(u,1,r.N),u=FW(u,2,r.K),u=FW(u,3,r.O),A=u.path,A.length)){h.push(A);C=d.B;D=d.b.J;H=d.b.K;r=0;for(K=A.length;r<K;r+=2)A[r]=(A[r]-D)*C-16,A[r+1]=(A[r+1]-H)*C-16;for(r=0;C=x[r];++r){A=C.offset;C=C.repeat;if(D=u.b){H=u.path;K=[];for(var G=0,O=H.length-
2;G<O;){var X=H[G],fa=H[G+1],Fa=D[G/2],Ea=Fa-A,G=G+2,Jb=H[G],bc=H[G+1];if(!(rY(X,fa)&rY(Jb,bc))){for(;_.ab(X,Jb)&&_.ab(fa,bc)&&G<O;)G+=2,Jb=H[G],bc=H[G+1];var Qc=D[G/2]-A,af=Math.atan2(Jb-X,fa-bc);0==Fa&&(Ea-=1E-9);if(C)for(Fa=Math.floor(Qc/C)*C;Fa>Ea;){var Di=(Fa-Ea)/(Qc-Ea);K.push(X+(Jb-X)*Di,fa+(bc-fa)*Di,af);Fa-=C}else 0>Ea&&0<=Qc&&(Ea=(0-Ea)/(Qc-Ea),K.push(X+(Jb-X)*Ea,fa+(bc-fa)*Ea,af))}}A=K}else A=null;A&&(l[r]=l[r].concat(A))}}}h.length&&(d={},d.b=h,d.l=l,d.f=a.style,d.zIndex=a.style.zIndex,
d.la=b,d.j=c,a=_.yb(d),c.ga[a]=d,b.ga[a]=d,b=b.b,b.f[_.yb(d)]=d,FY(b))},MY=function(a){return _.bb(a,function(a){var b={},d=a.path;if(50<=d.length){for(var e=[],f=d.length-2,g,h=2;h<f;h<<=1){for(var l=d[0],n=d[1],q=Math.ceil(f/(2*h)),r=Array(q),u=0,x=0,A=d.length-1-h;u<A;){var u=u+h,C=d[u],D=d[u+1],u=u+h;u>d.length-2&&(u=d.length-2);var H=d[u],K=d[u+1],G=C-l,O=D-n,l=H-l,X=K-n,fa=G*l+O*X,n=l*l+X*X;fa>=n?(C=H-C,D=K-D,D=C*C+D*D):0>=fa?D=G*G+O*O:(D=G*X-O*l,D*=D,D/=n+1E-16);D=Math.sqrt(D);g&&(D+=Math.max(g[2*
x],g[2*x+1]||0));r[x++]=D;l=H;n=K}x<q&&(r[x]=g?g[2*x]:0);g=r;e.push(r)}b.b=e}b.f=a;a=f=window.Infinity;e=g=-window.Infinity;h=0;for(q=d.length;h<q;)r=d[h++],a=Math.min(a,r),e=Math.max(e,r),r=d[h++],f=Math.min(f,r),g=Math.max(g,r);d=new _.uf;d.J=a;d.N=e;d.K=f;d.O=g;b.ta=d;return b})},PY=function(a,b,c,d){return _.bb(a,function(a){var e=a.path;a=a.b;var g=null;if(b){for(var g=c?NY(e):OY(e,d),h={0:0},l=0,n=[0],q=1,r=a.length;q<r;++q){var u=a[q];u in h?l=h[u]:(l+=g(q-1),h[u]=l);n.push(l)}g=n}return{path:e,
b:g}})},OY=function(a,b){var c=_.Va(a,0);KW(c,b);return function(a){a*=2;var b=c[a]-c[a+2];a=c[a+1]-c[a+3];return Math.sqrt(b*b+a*a)}},NY=function(a){return function(b){b*=2;var c=new _.E(a[b],a[b+1]);b=new _.E(a[b+2],a[b+3]);return _.Wy(c,b,1)}},TY=function(a){a.length&&(a=QY(a,RY),a=QY(a,SY));return a},QY=function(a,b){var c=[],d=new kX(0),e=new kX(0),f=new kX(0),g=Array(a.length);g[0]=a[0];g[1]=a[1];oX(a,d);for(var h=2,l=2;h<a.length;){c[0]=a[h];c[1]=a[h+1];oX(c,f);b(d,f,e)&&(pX(e,c),g[l++]=c[0],
g[l++]=c[1]);g[l++]=a[h++];g[l++]=a[h++];var n=d,d=f,f=n}return g},RY=function(a,b,c){if(0<a.z==0<b.z)return!1;nX(a,b,UY);nX(UY,VY,c);c.z=0;if(1E-12>lX(c,c))return!1;0>lX(c,a)+lX(c,b)&&(c.x=-c.x,c.y=-c.y);return!0},SY=function(a,b,c){nX(a,b,UY);nX(VY,UY,WY);nX(UY,WY,c);if(1E-12>lX(c,c)||0<lX(a,WY)==0<lX(b,WY))return!1;0>lX(c,a)+lX(c,b)&&(c.x=-c.x,c.y=-c.y,c.z=-c.z);return!0},YY=function(a,b,c){if(!b)return null;var d=[];b.forEach(function(a){d.push(XY(a))});a&&_.v(d,LW);if(c)for(a=0,b=d.length;a<
b;++a)d[a]=TY(d[a]);return d},ZY=function(a){return _.bb(a,function(a){var b;if(a.length){b=a[1];for(var d=[0],e=1,f=1;e<a.length/2;++e,++f){var g=a[2*e+1];if(180<Math.abs(b-g)){var h=g<b?1:-1,l=a[2*e-2],n=a[2*e];a.splice(2*e,0,n,g+360*h,n,g+450*h,90,g+450*h,90,b-450*h,l,b-450*h,l,b-360*h);d.push(f,f,f,f,f,f-1);e+=6}d.push(f);b=g}b=d}else b=[];return{path:a,b:b}})},XY=function(a){a=a.b;for(var b=a.length,c=Array(2*b),d=0,e=0;d<b;++d){var f=a[d];c[e++]=f.lat();c[e++]=f.lng()}return c},GX=function(a,
b){var c={},d=a.get("icons"),e=!a.Fa&&!!_.w(d),f=!0;c.b=[];e&&_.v(d,function(a){var b=lY(a.offset)||$Y;a=lY(a.repeat)||aZ;c.b.push({offset:b,repeat:a});f=f&&(0==b.value||"%"==b.Uc)&&(0==a.value||"%"==a.Uc)});var d=c.f=a.get("geodesic"),g=YY(a.Fa,a.get("latLngs"),d),g=ZY(g),h=d&&f;d&&e&&!h&&(g=bZ(g));g=PY(g,e,h,b);b=c.j=MY(g);if(1==b.length)e=b[0].ta;else for(e=new _.uf,d=0,g=b.length;d<g;++d)_.Sy(e,b[d].ta);c.ta=e;c.Nb=a;c.ga={};return c},bZ=function(a){return _.bb(a,function(a){return jY(a,_.ti,
.1)})},cZ=function(){var a=_.vG();this.j=_.PI;this.b=_.OI;this.f=a},FX=function(a,b){function c(a){return _.cb(b.get(a),f[a])}var d={},e=d.Fa=b.Fa,f=e?a.b:a.j;d.strokeColor=c("strokeColor");d.f=c("strokeOpacity");d.b=c("strokeWeight");d.eb=c("clickable");e?(d.l=c("strokePosition"),d.fillColor=c("fillColor"),d.j=c("fillOpacity")):d.l=a.b.strokePosition;var g=b.get("zIndex")||0;d.zIndex=1E3*g+_.yb(b)%1E3;d.b=Math.min(d.b,0==d.l?32:16);d.C=b.get("hitStrokeWeight")||dZ(d.b,d.l);d.m=[];d.B=1;if(!e){var e=
b.get("icons")||[],h=a.f,l=0;_.v(e,function(a){var b=h(a.icon||{},d.strokeColor,d.f,d.b);b.m=!a.fixedRotation;d.m.push(b);l=Math.max(l,b.f);l=Math.max(l,b.j)});_.ab(0,l)||(_.ab(0,d.f)||_.ab(0,d.b))&&1==d.m.length||(d.B=Math.max(l,d.f));_.w(e)&&(a=b.get("map"),_.Tm(a,"Os"),_.Vm("Os","-p",b,!(!a||!a.b)))}return d},dZ=function(a,b){switch(b){case 1:return 0;case 2:return 2*a;default:return a}},eZ=function(a){var b=a.__gm.F;if(!b.b){var c=a.__gm,d=new _.zc;(new JX(b,d,new cZ)).bindTo("projection",a);
var e=_.vf(-100,-200,100,200),f=new _.zc;new KY(d,new _.hG(e),f,new _.hG(e),!(!a||!a.b));d=_.nl(a.getDiv());d=new HY(new _.J(256,256),0,d);d=(0,_.p)(d.l,d);d=new zY(f,d);d.bindTo("projection",a);var g=new uY(f,c,function(b){return a.getProjection().fromPointToLatLng(b)});a.__gm.f.Ab(g);_.UF(a,d,"overlayLayer",30);var h=new UX;h.bindTo("panes",c);h.bindTo("projection",a);h.bindTo("zoom",c);h.bindTo("projectionCenterQ",c);h.bindTo("offset",c);_.z.bind(a,"click",h,h.wc);_.F("geometry",function(d){var e=
new xX(function(a,b,c){return a.get("geodesic")?new sX(a,b,c,d.computeHeading,d.computeOffset,d.computeOffsetOrigin):new uX(a,b,c)},a);AX(a,e);_.z.addListener(b,"insert",function(b){BX(b,e);yY(b,a,h,d.interpolate);DX(b,c,g,a.__gm.f);if(!b.j){var f=b.Fa?"Op":"Ol";_.Tm(a,f);_.Vm(f,"-p",b,!(!a||!a.b))}_.z.addListener(b,"click",function(){b.Fa?b.j||_.Vm("Op","-i",b,!(!a||!a.b)):_.Vm("Ol","-i",b,!(!a||!a.b))})})});_.z.addListener(b,"remove",function(a){_.v(a.G||[],_.z.removeListener);delete a.draggable_changed;
delete a.G;_.Wm("Od","-p",a);delete a.editable_changed;xY(a);_.z.trigger(h,"toolbar",{cb:!1,Fb:a});a.B&&(_.z.removeListener(a.B),delete a.B);_.Wm("Oe","-p",a);a.set("capturing",!1);delete a.capturing_changed;if(!a.j)if(a.Fa)_.Wm("Op","-p",a);else{_.Wm("Ol","-p",a);var b=a.get("icons");_.w(b)&&_.Wm("Os","-p",a)}})}},fZ=function(a,b,c){if(!a||!b||!c)return null;var d=c.lat(),e=c.lng();c=b&1?d:a.f.f;var f=b&2?e:a.b.b,d=b&4?d:a.f.b,g=b&8?e:a.b.f;if(c>d){var h=c;c=d;d=h}b&10&&!a.b.contains(e)&&(h=_.Ud(e,
a.b.b),a=_.Ud(a.b.f,e),b&2?h>a:a>h)&&(h=f,f=g,g=h);return _.Yd(c,f,d,g)},gZ=function(){var a=new _.vg({clickable:!1,fillOpacity:0});a.bindTo("map",this);a.bindTo("strokeColor",this);a.bindTo("strokeOpacity",this);a.bindTo("strokeWeight",this);var b=new _.eu(["bounds","freeControlPoint","freeVertexPosition"],"return",fZ);b.bindTo("bounds",this);b.bindTo("freeControlPoint",this);b.bindTo("freeVertexPosition",this);a.bindTo("bounds",b,"return");this.b=_.MI();this.b.bindTo("zIndex",this);a.bindTo("zIndex",
this.b,"ghostZIndex")},hZ=function(a,b){this.C=a;this.B=b;this.j=this.m=null;this.f=new _.yc;_.z.bind(this.f,"set_at",this,this.tp);this.l=new _.yc;_.z.bind(this.l,"set_at",this,this.up);this.b=!1},oZ=function(a,b,c){var d;d=c?new YW(a.f,iZ,jZ,!1,b.overlayMouseTarget,a.B):new YW(a.l,kZ,lZ,!0,b.overlayMouseTarget,a.B);d.bindTo("projection",a);d.bindTo("zoom",a);d.bindTo("projectionCenterQ",a);d.bindTo("panningEnabled",a);d.bindTo("mapPixelBounds",a);d.bindTo("color",a);d.bindTo("zIndex",a);d.bindTo("offset",
a);var e=a.C,f=c?mZ:nZ,g;_.z.addListener(d,"dragstart",function(b){g=a.get("bounds");e.bindTo("freeVertexPosition",d);e.set("freeControlPoint",f[b]);e.set("map",a.get("map"))});_.z.addListener(d,"dragend",function(b,c){e.set("map",null);_.z.trigger(a,"toolbar",{cb:!0,position:c,action:function(){a.set("bounds",g)}})});_.z.forward(d,"dragstart",a);_.z.forward(d,"dragend",a);_.z.forward(d,"panbynow",a);return d},pZ=function(a){a&&(a.unbindAll(),a.release(),_.z.clearInstanceListeners(a))},qZ=function(a,
b,c){a.b||(a.b=!0,b=fZ(a.get("bounds"),b,c),a.set("bounds",b),a.b=!1)},tZ=function(a,b){function c(){a.get("editable")?rZ(a,b):(sZ(a),_.z.trigger(a,"toolbar",{cb:!1}))}a.editable_changed=c;c()},rZ=function(a,b){if(!a.j){var c=new _.QI(a,!0);a.l=c;var d=new gZ;d.bindTo("strokeColor",c);d.bindTo("strokeOpacity",c,"ghostStrokeOpacity");d.bindTo("strokeWeight",c);d.bindTo("bounds",a);d.bindTo("zIndex",a);a.m=d;var e=b.__gm;a.b=HW(e);var f=_.cG(e,a),g=_.cl()?9:0,h=new dX,d=new hZ(d,function(b,c,d,e){return new RW(b,
a.b||null,g,c,f,d,h,e)});d.set("map",b);d.bindTo("bounds",a);d.bindTo("panes",e);d.bindTo("projection",b);d.bindTo("zoom",e);d.bindTo("projectionCenterQ",e);d.bindTo("panningEnabled",b,"draggable");d.bindTo("mapPixelBounds",e,"pixelBounds");d.bindTo("offset",e);d.bindTo("color",c,"strokeColor");d.bindTo("zIndex",a);d.bindTo("suppressGhostControlPoints",a);a.j=d;_.z.addListener(d,"dragstart",function(){a.set("capturing",!0)});_.z.addListener(d,"dragend",function(){a.set("capturing",!1)});_.z.forward(d,
"panbynow",e);_.z.forward(d,"toolbar",a)}},sZ=function(a){var b=a.j;b&&(b.unbindAll(),b.set("map",null),_.z.clearInstanceListeners(b),delete a.j,a.b.release(),delete a.b,a.set("capturing",!1),a.m.unbindAll(),delete a.m,a.l.release(),delete a.l)},uZ=function(a,b,c){this.j=a;this.ea=c;a=a.get("bounds");this.m=a.getSouthWest();this.l=a.getNorthEast();this.f=c.fromDivPixelToLatLng(b)},vZ=function(){var a=this,b=this.b=new _.Ce;b.j=!0;b.bindTo("capturing",a);b.bindTo("cursor",a);b.bindTo("map",a);b.bindTo("strokeColor",
a);b.bindTo("strokeOpacity",a);b.bindTo("strokeWeight",a);b.bindTo("strokePosition",a);b.bindTo("fillColor",a);b.bindTo("fillOpacity",a);b.bindTo("clickable",a);b.bindTo("zIndex",a);b.bindTo("suppressUndo",a);var c=this.f=[];_.v(PW,function(d){c.push(_.z.forward(b,d,a))});c.push(_.z.forward(a,"toolbar",b))},wZ=function(a){var b=a.__gm.G;if(!b.b){var c=new xX(function(a,b,c){return new uZ(a,b,c)},a);AX(a,c);b.b=function(b){BX(b,c);var d=b.yi=new vZ;d.set("map",a);d.bindTo("bounds",b);d.bindTo("capturing",
b);d.bindTo("cursor",b);d.bindTo("clickable",b);d.bindTo("fillColor",b);d.bindTo("fillOpacity",b);d.bindTo("strokeColor",b);d.bindTo("strokeOpacity",b);d.bindTo("strokeWeight",b);d.bindTo("strokePosition",b);d.bindTo("suppressUndo",b);d.bindTo("zIndex",b);var f=b.ba=[];_.v(PW,function(a){f.push(_.z.forward(d,a,b))});f.push(_.z.forward(b,"toolbar",d));tZ(b,a);_.Tm(a,"Or");_.Vm("Or","-p",b,!(!a||!a.b));_.z.addListener(b,"click",function(){_.Vm("Or","-i",b,!(!a||!a.b))})};b.onRemove=function(a){var b=
a.yi;b.unbindAll();b.set("map",null);b.release();delete a.yi;_.v(a.ba,_.z.removeListener);delete a.ba;delete a.editable_changed;sZ(a);_.Wm("Or","-p",a)}}},xZ=_.na();_.qf.prototype.Fd=_.aj(9,function(a,b){this.b==a&&this.f==b&&(this.f=this.b=null)});_.qf.prototype.Gd=_.aj(8,function(a,b){this.b=a;this.f=b});_.qf.prototype.Hd=_.aj(7,function(a){_.$i(this.l,a)});_.t(GW,_.B);GW.prototype.b=function(){return this.get("active")?this:null};
GW.prototype.handleEvent=function(a,b,c){if("mouseout"==a)this.set("cursor","");else if("mouseover"==a){var d=this.get("draggableCursor");d&&this.set("cursor",d)}_.z.trigger(c,a,new _.sk(b.latLng,b.xa))};GW.prototype.zIndex=window.Infinity;var PW="click dblclick mousedown mousemove mouseout mouseover mouseup rightclick".split(" ");_.t(NW,_.B);NW.prototype.f=function(a,b,c,d,e){return!e&&d&&a?_.Wy(d,a,c):b};_.t(RW,_.B);RW.prototype.release=function(){_.ig(this.b);_.v(this.R,_.z.removeListener);this.R.length=0;this.j.unbindAll();this.j.release();this.F.unbindAll();this.m.set("active",!1)};RW.prototype.position_changed=function(){var a=this.get("position");if(a){var b=5+this.B;_.ol(this.b,new _.I(a.x-b,a.y-b))}};RW.prototype.color_changed=function(){var a=this.get("color");this.b.firstChild.style.borderColor=a;OW(this)};_.t(YW,_.B);YW.prototype.release=function(){_.v(this.F,_.z.removeListener);this.F.length=0;_.v(this.b,(0,_.p)(this.G,this));this.b.length=0;_.z.clearInstanceListeners(this.f);_.ig(this.f)};YW.prototype.zIndex_changed=function(){var a=this.get("zIndex")||0;this.l&&--a;_.Yl(this.f,a)};
YW.prototype.m=function(a,b){function c(a){var b=e.index,c=f.get("pixelPosition");_.z.trigger(d,a,b,c)}var d=this,e={};e.index=b;d.b.splice(b,0,e);var f=new _.KF;f.bindTo("projection",d);f.bindTo("zoom",d);f.bindTo("center",d,"projectionCenterQ");f.bindTo("offset",d);f.set("latLngPosition",a);e.Lc=f;var g=this.H(d.f,d.C[b%d.C.length],d.B[b%d.B.length],d.l);g.bindTo("position",f,"pixelPosition");g.bindTo("color",d);g.bindTo("panningEnabled",d);g.bindTo("mapPixelBounds",d);e.b=g;var h=[_.z.addListener(g,
"dragstart",function(){d.bindTo("freeVertexPosition",f,"latLngPosition");c("dragstart")}),_.z.addListener(g,"dragend",function(){d.M.setAt(e.index,f.get("latLngPosition"));c("dragend")}),_.z.forward(g,"panbynow",d)];_.v(PW,function(a){h.push(_.z.addListener(g,a,function(){c(a)}))});e.ba=h};YW.prototype.G=function(a){a.b.unbindAll();a.b.release();a.Lc.unbindAll();_.v(a.ba,_.z.removeListener);a.ba.length=0};_.t(ZW,_.B);var $W=["pointer","row-resize","row-resize","col-resize","col-resize"],aX=[0,2,2,1,1];_.k=ZW.prototype;_.k.map_changed=function(){this.get("map")||(this.l.set("map",null),cX(this),_.z.clearInstanceListeners(this.b))};_.k.panes_changed=function(){cX(this);this.j=bX(this)};
_.k.cg=function(){var a=this.b;a.clear();var b=this.get("center"),c=this.get("radius");if(b&&_.y(c)){var d=this.get("planetRadius"),e=_.Tb(c/d),f;f=_.Sb(b.lat());if(d=c/d){var c=Math.cos(d),d=Math.sin(d),g=Math.sin(f);f=Math.atan2(Math.sin(Math.acos((1-c)/d*Math.tan(f)))*d*Math.cos(f),c-g*g)}else f=0;f=_.Tb(f);a.push(b);c=b.lat()+e;90>c&&a.push(new _.E(c,b.lng()));e=b.lat()-e;-90<e&&a.push(new _.E(e,b.lng()));180>=f&&(e=b.lng()+f,f=b.lng()-f,a.push(new _.E(b.lat(),e)),a.push(new _.E(b.lat(),f)));
this.f||_.z.trigger(this,"toolbar",{cb:!1})}};_.k.center_changed=ZW.prototype.cg;_.k.radius_changed=ZW.prototype.cg;_.k.planetRadius_changed=ZW.prototype.cg;_.k.vp=function(a){var b=this.b.getAt(a);if(0==a)_.az(this,function(){this.f=!0;this.set("center",b);this.f=!1},0);else{var c=_.Wy(this.get("center"),b,this.get("planetRadius"));_.az(this,function(){this.f=!0;this.set("radius",c);this.f=!1},0)}};dX.prototype.construct=function(a,b,c,d,e){a=_.Y("div",a,new _.I(b,b),new _.J(c,c));a.style.borderWidth=_.V(d);a.style.borderStyle="solid";a.style.borderRadius=_.V(Math.ceil(c/2+d));_.am(a,e)};var yZ=new _.E(90,0),zZ=new _.E(-90,0);hX.prototype.b=function(a){a=this.ea.fromDivPixelToLatLng(a);var b=this.l(a,this.f,this.m);b||(b=Math.abs(_.Wy(a,yZ)-this.f)<Math.abs(_.Wy(a,zZ)-this.f)?yZ:zZ);this.j.set("center",b)};_.t(iX,_.yf);_.k=iX.prototype;_.k.center_changed=iX.prototype.L;_.k.radius_changed=iX.prototype.L;_.k.planetRadius_changed=iX.prototype.L;_.k.Z=function(){var a=this.b;if(a){var b=this.get("radius"),c=this.get("center");_.y(b)&&c?(b/=this.get("planetRadius"),a.setPaths(jX(c,b))):a.setPaths([])}};_.k.release=function(){for(var a=this.f,b=0,c=a.length;b<c;++b)_.z.removeListener(a[b]);this.f=null;this.b.unbindAll();this.b=null};sX.prototype.b=function(a){var b=this;a=b.ea.fromDivPixelToLatLng(a);var c=this.B(a,this.F,this.G);c?89<Math.abs(c.lat())&&(c=new _.E(_.Za(c.lat(),-89,89),c.lng())):c=new _.E(this.j.lat(),a.lng()-this.l);b.f.get("latLngs").forEach(function(a,e){for(var d=0,g=a.getLength();d<g;++d){var h=b.C(c,b.m[e][d].ec,b.m[e][d].heading);a.setAt(d,h)}});this.j=c;this.l=a.lng()-c.lng()};_.t(tX,_.sk);uX.prototype.b=function(a){var b=this.j.get("latLngs"),c=this.ea,d=c.fromLatLngToDivPixel(this.f),e=new _.I(d.x-a.x,d.y-a.y);_.v(this.l,function(a,d){var f=b.getAt(d);_.v(a,function(a,b){a=c.fromLatLngToDivPixel(a);a.x-=e.x;a.y-=e.y;f.setAt(b,c.fromDivPixelToLatLng(a))})})};_.t(xX,_.B);xX.prototype.release=function(){this.j&&(this.j.unbindAll(),this.j.release(),this.j=null);this.B&&_.v(this.B,_.z.removeListener);this.B=null;this.R&&_.v(this.R,_.z.removeListener);this.R=null;this.f&&_.Ak(this.f);this.f=null};var vX=new _.J(30,30),wX=new _.I(vX.width/2,vX.height/2);_.k=xX.prototype;
_.k.Fe=function(){if(!this.get("active")&&!this.m){var a=this.get("panes"),b=this.get("projectionController"),c=this.get("poly");if(a!=this.l||b!=this.ea||c!=this.b)this.l=a,this.ea=b,this.b=c,this.R&&_.v(this.R,_.z.removeListener),this.R=null,this.l&&this.ea&&this.b?(this.R=_.cl()?[_.z.bind(this.b,"mousedown",this,this.Jn),_.z.bind(this.b,"mouseup",this,this.Ln)]:[_.z.bind(this.b,"mousemove",this,this.Kn)],this.bindTo("draggable",this.b)):(this.unbind("draggable"),this.set("draggable",!1))}};
_.k.active_changed=xX.prototype.Fe;_.k.panes_changed=xX.prototype.Fe;_.k.poly_changed=xX.prototype.Fe;_.k.projectionController_changed=xX.prototype.Fe;_.k.draggable_changed=function(){this.get("draggable")&&!_.cl()?(this.l.overlayMouseTarget.appendChild(this.f),yX(this,!!this.get("active"))):this.f&&this.f.parentNode&&this.f.parentNode.removeChild(this.f)};_.k.dk=function(a){_.ob(a);zX(this,"click",a)};_.k.hk=function(a){this.set("mousedown",!0);yX(this,!0);zX(this,"mousedown",a)};
_.k.jk=function(a){yX(this,!1);this.set("mousedown",!1);zX(this,"mouseup",a)};_.k.ik=function(a){this.get("active")?_.ob(a):zX(this,"mousemove",a)};_.k.Kn=function(a){if(a=a.xa)a=_.Sm(a,this.l.overlayMouseTarget),this.set("position",a)};_.k.Dg=function(){var a=this.get("position");this.set("dragging",!0);this.G=this.C(this.b,a,this.ea);this.b.set("capturing",!0);zX(this,"dragstart");this.F=this.b.get("editable");this.b.set("editable",!1)};
_.k.af=function(){this.b.set("editable",this.F);zX(this,"dragend");this.b.set("capturing",!1);this.set("dragging",!1)};_.k.position_changed=function(){var a=this.get("position");_.cl()||_.ol(this.f,new _.I(a.x-wX.x,a.y-wX.y));this.get("dragging")&&(this.G.b(a),zX(this,"drag"))};_.k.fk=function(a){a&&_.ht(a)||!this.m||!this.b||this.get("dragging")||(a=this.ea.fromLatLngToDivPixel(a.latLng),this.set("position",a),this.Dg())};
_.k.gk=function(a){if(this.get("dragging")){if(1!=a.scale)this.af();else if(this.m){var b=this.ea.fromLatLngToDivPixel(a.latLng);this.set("position",b)}_.Wz(a)}};_.k.ek=function(a){this.get("dragging")&&(this.af(),_.Wz(a))};_.k.Jn=function(){this.m=!!this.get("draggable")};_.k.Ln=function(){this.m=!1};_.t(JX,_.B);JX.prototype.projection_changed=function(){var a=this;a.C.forEach(function(b){if(b.get("icons")){var c=_.yb(b);a.b[c]=b;IX(b)}});MX(a)};var KX={latLngs:1,geodesic:1,icons:1},LX={strokeColor:1,strokeOpacity:1,strokePosition:1,strokeWeight:1,fillColor:1,fillOpacity:1,hitStrokeWeight:1,zIndex:1,clickable:1,icons:1};_.t(UX,_.B);_.k=UX.prototype;_.k.panes_changed=function(){var a=this.f,b=this.get("panes");b?b.floatPane.appendChild(a):a.parentNode&&_.ig(a)};_.k.wc=function(){_.kA(this.f);this.l=null;VX(this);this.j=null};_.k.changed=UX.prototype.wc;_.k.kk=function(a){a.cb?a.Fb.get("suppressUndo")?this.wc():XX(this,a.position,a.action,a.Fb):a.Fb==this.j&&this.wc()};_.k.Zn=function(a){_.nb(a);_.ob(a);this.l();this.wc()};_.k.Ee=function(a){_.$z(this.b,RX,a)};
var PX=_.lm("undo_poly"),RX=new _.J(30,27),QX=_.Yg,SX=new _.I(30,0),TX=new _.I(60,0),WX=new _.I(10,-11);YX.prototype.getLength=function(){var a=this.b.getLength();1<a&&++a;return a};YX.prototype.getAt=function(a){this.b.getLength()==a&&1<a&&(a=0);return this.b.getAt(a)};_.t(ZX,_.B);_.k=ZX.prototype;_.k.release=function(){_.v(this.R,_.z.removeListener)};_.k.lo=function(){var a=this.get("projection"),b=this.j;if(a)for(var c=this.f,d=c.getLength(),e=this.get("geodesic"),f=0;f<d-1;++f)b.setAt(f,$X(c.getAt(f),c.getAt(f+1),e,a,this.b));else b.clear()};_.k.geodesic_changed=ZX.prototype.projection_changed=ZX.prototype.lo;_.k.zj=function(a){aY(this,!1,a)};_.k.vg=function(a){aY(this,!0,a)};
_.k.yj=function(a){var b=this.get("projection");if(b){var c=this.f,d=this.j,e=this.get("geodesic");a<c.getLength()?(0<a&&d.setAt(a-1,$X(c.getAt(a-1),c.getAt(a),e,b,this.b)),d.removeAt(a)):0<a&&d.removeAt(a-1)}};_.t(bY,_.B);bY.prototype.map_changed=function(){this.get("map")||(this.m.set("map",null),fY(this))};
bY.prototype.panes_changed=bY.prototype.paths_changed=bY.prototype.suppressGhostControlPoints_changed=function(){var a=this;fY(a);var b=a.get("paths"),c=a.get("panes");if(b&&c){var d=c.overlayMouseTarget;b.forEach(function(b){a.f.push(dY(a,b,d));a.get("suppressGhostControlPoints")||a.b.push(eY(a,b,d))});var e=function(){_.z.trigger(a,"toolbar",{cb:!1})};e();c=a.B;c.push(_.z.addListener(b,"insert_at",function(c){var f=a.get("suppressGhostControlPoints"),h=b.getAt(c);a.f.splice(c,0,dY(a,h,d));f||a.b.splice(c,
0,eY(a,h,d));e()}));c.push(_.z.addListener(b,"remove_at",function(b){var c=a.get("suppressGhostControlPoints");a.j(a.f[b]);a.f.splice(b,1);c||(a.j(a.b[b]),a.b.splice(b,1));e()}));c.push(_.z.addListener(b,"set_at",function(c){var f=a.get("suppressGhostControlPoints");a.j(a.f[c]);var h=b.getAt(c);a.f[c]=dY(a,h,d);f||(a.j(a.b[c]),a.b[c]=eY(a,h,d));e()}))}};bY.prototype.j=function(a){a.unbindAll();a.release();_.z.clearInstanceListeners(a);a.j&&(a.j.release(),a.j.unbindAll())};var kY={};tY.prototype.getBounds=_.pa("f");uY.prototype.b=function(a,b){var c=a.da,d=null,e=new _.I(0,0),f=new _.I(0,0),g;this.j.forEach(function(a){if(!d){g=1<<a.zoom;f.x=256*a.Y.x;f.y=256*a.Y.y;var b=e.x=Math.round(c.x*g-f.x)+.5,h=e.y=Math.round(c.y*g-f.y)+.5;0<=b&&256>b&&0<=h&&256>h&&(d=a)}});if(!d)return null;var h=[],l=d.ga,n;for(n in l)h.push(l[n]);h.reverse();h.sort(function(a,b){return b.zIndex-a.zIndex||0});l=null;n=b?15:0;for(var q=0,r=h.length;q<r;++q){var u=h[q],x=u.f;if(x.eb){var A=u.j.Nb,C=x.C/2+n,u=vY(u.b);if(C=IW(e.x,e.y,C,
u)){l=A;b=a.da=new _.I((C[0]+f.x)/g,(C[1]+f.y)/g);a.latLng=this.l(b);break}if(x.Fa&&!b&&JW(e.x,e.y,u)){l=A;break}}}return l};uY.prototype.handleEvent=function(a,b,c){if("mouseout"==a)this.f.set("cursor","");else if("mousemove"==a){var d=c.get&&c.get("cursor");_.m(d)||(d="pointer");this.f.set("cursor",d)}_.z.trigger(c,a,new tX(b.latLng,b.xa))};uY.prototype.zIndex=30;_.t(zY,_.B);zY.prototype.projection=null;zY.prototype.maxZoom=30;zY.prototype.getTile=function(a,b,c){c=c.createElement("div");_.zf(c,this.tileSize);c.style.overflow="hidden";var d=this.get("projection"),d=new tY(a,b,d),e=d.getBounds(),f=this.f(c),g={};g.ta=e;g.Y=a;g.U=c;g.b=f;g.ga={};g.f=d;g.zoom=b;c.la=g;_.Ac(this.b,g);return c};zY.prototype.releaseTile=function(a){var b=a.la;a.la=null;this.b.remove(b);_.ql(a,"")};HY.prototype.l=function(a,b){this.b||(this.b=GY(this.f,a));return new CY(b,this.j,this.b,a)};var VY=new kX(1),UY=new kX(0),WY=new kX(0);var $Y={value:100,Uc:"%"},aZ={value:0,Uc:"px"};_.t(gZ,_.B);_.t(hZ,_.B);var mZ=[12,6,9,3],nZ=[1,2,4,8],iZ=["ne-resize","nw-resize","se-resize","sw-resize"],kZ=["row-resize","col-resize"],jZ=[0],lZ=[2,1];_.k=hZ.prototype;_.k.map_changed=function(){this.get("map")||(this.C.set("map",null),pZ(this.m),this.get("suppressGhostControlPoints")||pZ(this.j),_.z.clearInstanceListeners(this.f))};
_.k.panes_changed=hZ.prototype.suppressGhostControlPoints_changed=function(){pZ(this.m);pZ(this.j);this.j=null;var a=this.get("panes");a&&(this.m=oZ(this,a,!0),this.get("suppressGhostControlPoints")||(this.j=oZ(this,a,!1)))};
_.k.bounds_changed=function(){var a=this.f,b=this.l,c=this.get("bounds");if(c){this.b=!0;a.setAt(0,c.getNorthEast());a.setAt(1,new _.E(c.f.b,c.b.b,!0));a.setAt(2,_.Ty(c));a.setAt(3,c.getSouthWest());var a=c.f.Mb(),d=c.b.Mb();b.setAt(0,new _.E(c.f.f,d));b.setAt(1,new _.E(a,c.b.b));b.setAt(2,new _.E(c.f.b,d));b.setAt(3,new _.E(a,c.b.f));this.b=!1;_.z.trigger(this,"toolbar",{cb:!1})}else a.clear(),b.clear()};_.k.tp=function(a){qZ(this,mZ[a],this.f.getAt(a))};_.k.up=function(a){qZ(this,nZ[a],this.l.getAt(a))};uZ.prototype.b=function(a){var b=this.ea,c=b.fromLatLngToDivPixel(this.f),d=b.fromLatLngToDivPixel(this.m),b=b.fromLatLngToDivPixel(this.l),b=new _.I(b.x-c.x+a.x,b.y-c.y+a.y);a=new _.Xd(this.ea.fromDivPixelToLatLng(new _.I(d.x-c.x+a.x,d.y-c.y+a.y)),this.ea.fromDivPixelToLatLng(b));this.j.set("bounds",a)};_.t(vZ,_.B);vZ.prototype.bounds_changed=function(){var a=this.b;if(a){var b=this.get("bounds");if(b){var c=b.getSouthWest(),d=b.getNorthEast(),b=b.getCenter();a.setPaths([new _.E(d.lat(),d.lng()),new _.E(d.lat(),b.lng()),new _.E(d.lat(),c.lng()),new _.E(c.lat(),c.lng()),new _.E(c.lat(),b.lng()),new _.E(c.lat(),d.lng())])}else a.setPaths([])}};vZ.prototype.release=function(){for(var a=this.f,b=0,c=a.length;b<c;++b)_.z.removeListener(a[b]);delete this.f;this.b.unbindAll();delete this.b};xZ.prototype.b=function(a){var b=0!=a.getVisible()?a.getMap():null;a.f!=b&&(a.f&&a.f.__gm.l.remove(a),b&&(CX(b),_.Ac(b.__gm.l,a)),a.f=b)};xZ.prototype.f=function(a){var b=0!=a.getVisible()?a.getMap():null;a.l!=b&&(a.l&&a.l.__gm.F.remove(a),b&&(eZ(b),_.Ac(b.__gm.F,a)),a.l=b)};xZ.prototype.j=function(a){var b=0!=a.getVisible()?a.getMap():null;a.f!=b&&(a.f&&a.f.__gm.G.remove(a),b&&(wZ(b),_.Ac(b.__gm.G,a)),a.f=b)};_.mc("poly",new xZ);});
